### ISSUE TITLE
Display BAMs on run page

### ISSUE THREAD

**Issue by arahuja** [hammerlab/cycledash#584]
Perhaps my understanding of `Project` is incorrect here, but I've assuming a project has many BAMs and each run is using some subset of them (usually 2).  It would nice to display the BAMs that a run uses directly.  Specifically displaying the entered `name` when a BAM entry is created (this can be linked from the path, correct?)

**Comment by ihodes** [comment]
Your assumption is indeed correct. Would replacing the path of the BAM (shown when clicking on a run) with the name of the BAM (if entered) get you where you want to be? Also, because it's probably not clear from the UI, you can click "N BAMs" on the upper-right of the project to see a list of all associated BAMs.

**Comment by arahuja** [comment]
I think see the full path when expanded is actually nice, but adding in the labels could be helpful.  Perhaps changing the `tumor`, `normal` tags that appear with the label of the bam files used?  Otherwise almost all of them will be say tumor/normal which doesn't add much.

![image](https://cloud.githubusercontent.com/assets/455755/7507684/ae1d4e60-f441-11e4-89ba-4472c3c78e57.png)
